language: node_js
os:
  - linux
node_js: 8

install:
  - npm install

branches:
  except:
  - gh-pages

stages:
  - lint
  - test
  - build

jobs:
  include:
    - stage: lint
      script:
        # Run linter
        - npm run lint -- --no-fix
    - stage: test
      script:
        # Run tests
        - npm run coverage:unit
        - bash <(curl -s https://codecov.io/bash)
    - stage: build
      script:
        # Build all
        - npm run build
